//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HayvonotOlamiBolalarEnsiklopediyasi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HayvonotOlamiBolalarEnsiklopediyasi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon chihuahua_bone_dog_animal_15961 {
            get {
                object obj = ResourceManager.GetObject("chihuahua_bone_dog_animal_15961", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p1_1 {
            get {
                object obj = ResourceManager.GetObject("p1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p1_2 {
            get {
                object obj = ResourceManager.GetObject("p1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p10_1 {
            get {
                object obj = ResourceManager.GetObject("p10_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p10_2 {
            get {
                object obj = ResourceManager.GetObject("p10_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p11_1 {
            get {
                object obj = ResourceManager.GetObject("p11_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p11_2 {
            get {
                object obj = ResourceManager.GetObject("p11_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p12_1 {
            get {
                object obj = ResourceManager.GetObject("p12_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p12_2 {
            get {
                object obj = ResourceManager.GetObject("p12_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p13_1 {
            get {
                object obj = ResourceManager.GetObject("p13_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p13_2 {
            get {
                object obj = ResourceManager.GetObject("p13_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p14_1 {
            get {
                object obj = ResourceManager.GetObject("p14_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p14_2 {
            get {
                object obj = ResourceManager.GetObject("p14_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p15_1 {
            get {
                object obj = ResourceManager.GetObject("p15_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p15_2 {
            get {
                object obj = ResourceManager.GetObject("p15_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p16_1 {
            get {
                object obj = ResourceManager.GetObject("p16_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p16_2 {
            get {
                object obj = ResourceManager.GetObject("p16_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p17_1 {
            get {
                object obj = ResourceManager.GetObject("p17_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p17_2 {
            get {
                object obj = ResourceManager.GetObject("p17_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p18_1 {
            get {
                object obj = ResourceManager.GetObject("p18_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p18_2 {
            get {
                object obj = ResourceManager.GetObject("p18_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p2_1 {
            get {
                object obj = ResourceManager.GetObject("p2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p2_2 {
            get {
                object obj = ResourceManager.GetObject("p2_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p3_1 {
            get {
                object obj = ResourceManager.GetObject("p3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p3_2 {
            get {
                object obj = ResourceManager.GetObject("p3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p4_1 {
            get {
                object obj = ResourceManager.GetObject("p4_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p4_2 {
            get {
                object obj = ResourceManager.GetObject("p4_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p5_1 {
            get {
                object obj = ResourceManager.GetObject("p5_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p5_2 {
            get {
                object obj = ResourceManager.GetObject("p5_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p6_1 {
            get {
                object obj = ResourceManager.GetObject("p6_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p6_2 {
            get {
                object obj = ResourceManager.GetObject("p6_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p7_1 {
            get {
                object obj = ResourceManager.GetObject("p7_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p7_2 {
            get {
                object obj = ResourceManager.GetObject("p7_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p8_1 {
            get {
                object obj = ResourceManager.GetObject("p8_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p8_2 {
            get {
                object obj = ResourceManager.GetObject("p8_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p9_1 {
            get {
                object obj = ResourceManager.GetObject("p9_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p9_2 {
            get {
                object obj = ResourceManager.GetObject("p9_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timsohlar — suvda yashovchi sudralib yuruvchilar turkumi. Tanasi kaltakesakka oʻxshash, uzunligi 2–7 m, boshi yassilashgan, tumshugʻi uzun. Koʻzlari va burun teshiklari boshi ustidan boʻrtib chiqib turadi. Burun va quloq teshiklari suvda yopiladigan klapanlar bilan taʼminlangan. Ogʻiz boʻshligʻida ikkilamchi tanglay boʻladi. Tishlari yirik. Tili ogʻiz tubiga yopishgan. Dumi uzun va baland (ikki yondan yassilashgan). Orqa oyoqlari barmoqlari orasida suzgich pardalari bor. Terisi qattiq va qalin, muguzsimon y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s1 {
            get {
                return ResourceManager.GetString("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chayonlar — oʻrgimchaksimonlar turkumi, baʼzan mustaqil sinf sifatida qaraladi. Uzunligi 1—20 sm. Boshkoʻkragi yaxlit qalqon bilan qoplangan. Bu qalqon oʻrtasida 2 juft, uning 2 yonida bir necha juft koʻzlari bor. Kutikulasi mum qavati bilan qoplangan. Korin qismi kengaygan. Ingichka keyingi boʻlimi boshkoʻkrak tomoniga egiluvchan. Bir juft zahar bezi keyingi qorinning oxirgi boʻgʻimida joylashgan boʻlib, sanchuvchi nashtarga ochiladi. Xelitseralari mayda, qiskichsimon. Oyoq paypaslagichlari uchki kismi yir [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s10 {
            get {
                return ResourceManager.GetString("s10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boyoʻgʻlilar, boyqushlar— yapaloqqushlar oilasiga mansub tungi yirtqich qushlar urugʻi. Yevropa, Osiyo, Amerika va Afrikada tarqalgan, 20 tacha turi bor. Oʻzbekistonda bir turi — uy boyoʻgʻlisi uchraydi. Oyoqlari kuchli va paxmoq, tumshugʻi qayrilgan, pati mayin, tovushsiz uchib kelib, oʻljasini tutib oladi. Koʻzlari oʻtkirligidan salgina yorugʻni ham sezadi. Xira kulrang pati qorongʻida koʻzga chalinmaydi. Boyoʻgʻlilarning bu turi Yevropa, Shimoliy Afrika, Osiyoda ham tarqalgan. Uni dasht va choʻllarda, ha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s11 {
            get {
                return ResourceManager.GetString("s11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sirtlonlar— yirtqichlar turkumiga mansub sut emizuvchilar oilasi. Tashqi koʻrinishi buriga oʻxshaydi. Gavdasining uzunligi 55—165 sm. Oldingi oyoklari orqadagisiga nisbatan uzunroq. Oyoqlari 4 barmokli, boʻyni yoʻgʻon, boshi katta, tishlari yirik. Dumi pahmoq, kalta (uzunligi 20—22 sm). Koʻpchiligining boʻyni ustida va qisman yagʻrinida uzun yungi (yoli) boʻladi. Qoʻngʻir yoki kulrangtusli yungi yoʻl-yoʻl yoki xoldor. Afrika, Old va Oʻrta Osiyo, Janubi-Gʻarbiy Osiyoda tarkalgan. Oʻzbekiston janubida (Surxon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s12 {
            get {
                return ResourceManager.GetString("s12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qoplon, qor qoploni, irbis — mushuksimonlar oilasiga mansub sut emizuvchi; urugʻning yagona turi. Baʼzan yirik mushuksimonlar urugʻiga kiritiladi. Gavdasining uz. 103—130 sm, ogʻirligi 70 kg gacha. Tanasi choʻziq, oyoqlari qisqa. Moʻynasi qalin, sargʻish tusda, qora halqa dogʻlari bor. Asosan, Markaziy va Oʻrta Osiyodagi baland togʻlarda, odatda, 2000 m dan balandroqda doimiy qorli togʻ tizmalarida uchraydi. Qishda pastroqqa — ninabargli oʻrmonlar mintaqasigacha tushadi. Oʻrta Osiyoda jan.-gʻarbiy Turkiston [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s13 {
            get {
                return ResourceManager.GetString("s13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anakondalar– boʻgʻma ilonlar urugʻi. Hozirgi ilonlarning eng yirigi – uzunligi 10 m gacha (qayd qilingan uzunligi 11,43 m). Sargʻish-kulrang tanasi orqa tomondan 2 qator yirik doira shakli-dagi qoʻngʻir, yon tomonlardan bir necha qator mayda oqish dogʻlar bilan qoplangan. 3 turi tropik. Janubiy Amerikaning daryo, koʻl va botqoqliklarida tarqalgan. Oddiy Anakondalar kuproq uchraydi. Anakondalar suvda yaxshi suzadi va shoʻngʻiydi, suv tubida uzoq tura oladi. Suv ostida burun teshiklari klapanlari bekiladi. An [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s14 {
            get {
                return ResourceManager.GetString("s14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meduzalar — boʻshliqichlilarning , koʻpincha, erkin yashovchi jinsiy avlodi. Gavdasi xira shaffof (mezogliysi kuchli rivojlanganligi tufayli), soyabon yoki qoʻngʻiroq shaklda, diametri bir necha mm dan 2–3 m gacha. Soyaboni chetlarida paypaslagichlari (uzunligi 30 sm gacha) va sezgi organlari joylashgan. Ogʻzi soyabonining ostki botiq tomoni oʻrtasida boʻlib, odatda, ogʻiz parraklari bilan oʻralgan. Meduzalar  soyaboni ostida suvni siqib chiqarishi tufayli reaktiv usulda harakatlanadi. Ayrim ssifomeduzalar  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s15 {
            get {
                return ResourceManager.GetString("s15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaguar — katta mushuklar urugʻiga mansub yirtqich sut emizuvchi. Gavdasining uz. 2 m gacha, dumi 75 sm gacha. Jussasining koʻrinishi yoʻlbarsga oʻxshash; qizgʻish yungida qora dogʻlari va halqalari boʻladi. Janubiy, Markaziy Amerika va Shim. Amerikaning janubida tarqalgan. Tropik va subtropik oʻrmonlarda, ahyonahyonda togʻlarda uchraydi. Daraxtlarga chiqa oladi. Tuyoqlilar, maymunlar va kemiruvchilar bilan oziklanadi. Soni kamayib ketgan. Tabiatni muhofaza qilish xalqaro ittifoqi Qizil kitobiga kiritilgan..
        /// </summary>
        internal static string s16 {
            get {
                return ResourceManager.GetString("s16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begemotlar ,suv aygʻirlari— juft tuyoqlilar turkumiga mansub kavsh qaytarmaydigan sut emizuvchilar. Terisi qalin, siyrak yung bilan qoplangan, oyoqlari kalta, tushmugʻining uchki qismi kengaygan, oshqozoni 3 boʻlmali, pastki kurak va qoziq tishlari doim oʻsib turadi. Afrikaning tinch oqadigan va botqoklashgan suv havzalarida yashaydi. Bitta bola tugʻadi. 2 urugʻining bittadan turi bor. Odsiy suv aygʻiri, yaʼni gippopotam  gavdasining uzunligi 4,0—4,5 metr, dumi 35—50 sm. vazni 1,3—3,2 (baʼzan 4,5) tonna. Bo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s17 {
            get {
                return ResourceManager.GetString("s17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echkemarlar — kaltakesaklar kenja turkumiga mansub sudralib yuruvchilar oilasi. Hozir yashab turgan bir urugʻi (Varanus) mavjud. Tanasi choʻziq, oyoqlari yaxshi rivojlangan, dumi koʻpchilik turlarida yon tomondan siqilgan. Boshi mayda qalqonchalar bilan qoplangan. Tanasidagi tangachalar yumaloq, botiq. Tili uzun, uchi ikki ayrili. 24 turi bor. Sharqiy yarim shardagi tropik, subtropik va qisman moʻʼtadil mintaqalarda tarqalgan. Madagaskarda uchramaydi. Odatda, ochiq yerlarda, daryo va boshqalar chuchuk suv h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s18 {
            get {
                return ResourceManager.GetString("s18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kobra — O‘zbekistondagi yirik zaharli ilonlardan biridir Tanasining uzunligi 125 sm, dumi 45 sm gacha. Rangi tana rangidan to‘q sariq, qo‘ng‘ir yoki qoragacha kuchli darajada o‘zgarib turadi. Ostki tomoni oq va tanasining oldingi tomonida ikki-uchta qora ko‘ndalang yo‘llari bor. Yoshlarining orqasida uzunasiga qora rangli ko‘ndalang yo‘llari bor, ularning old tomonidagilari pastki yuzasiga o‘tib ketadi. Hindistonda yashaydigan kobralarning ensasida ko‘zoynakka o‘xshash naqshi bo‘lgani uchun ular ko‘zoynakli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s2 {
            get {
                return ResourceManager.GetString("s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arslon yoki sher -mushuksimonlar oilasiga mansub turdir. Uzunligi 240 sm gacha (urgʻochisi kichikroq), ogʻirligi 280 kg gacha boʻladi. Yuz qismi choʻziq, dumining uchida uzun qora qildan iborat popugi bor. Tanasi kalta jun bilan qoplangan, erkaklari tanasining oldingi qismi (boʻyni, koʻkragi va yuzi)dagi uzun yunglari yolni hosil qiladi. Rangi sargʻish, yoli qoramtir tusda. Qadimgi areali Afrika (gʻarbidan tashqari), Yevropa (Bolqon yarim oroli, Zakavkaze – Armaniston) hamda Osiyoni (Arabiston yarim oroli,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s3 {
            get {
                return ResourceManager.GetString("s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akulalar (Selachomorpha) – tog‘ayli baliqlar sinfi plastinka jabralilar kenja sinfining katta turkumi. Tanasi suyri shaklda, suv tubida yashovchi A. yassi, uz. 15–40 sm dan (tikanli qora Akula) 15–20 m gacha (gigant Akula), og‘irligi 14 t gacha (gigant va kit Akula). Tanasi plakoid tangachalar bilan krplangan. Jabra yoriqlari 5 (ba’zi turlarida 6–7) tadan bo‘lib, boshining ikki yonida, og‘zi boshining ostida tanasiga ko‘ndalang joylashgan. Dum suzgichi kuchli rivojlangan, har xil kattalikdagi (gsterotserkal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s4 {
            get {
                return ResourceManager.GetString("s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boʻri, qashqir— itsimonlar oilasiga mansub yirtqich sut emizuvchi hayvon. Yevropa, Osiyo va Shimoliy Amerikada tarqalgan. Oʻzbekistonning choʻl, dashtlari, oʻrmon, toʻqay, togʻ va togʻ etaklarida tarqalgan; qor va muz bilan qoplangan baland togʻlar va tundrada ham yashaydi.
        ///Boʻrilar qoyalar orasiga, toʻqaylik va jarliklarga, quruq qamishzorlarga in quradi. Tulki inlaridan ham foydalanadi. Boʻrilar inida bolalaydi va bolalarini parvarish qiladi. Chorvachilik r-nlarida podalardan uzoqqa ketmaydi. Boʻrilar ya [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s5 {
            get {
                return ResourceManager.GetString("s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burgut — yirtqichlar turkumining qirgʻiylar oilasiga mansub qush. Burgut yirik, chaqqon va kuchli. Tanasining uz. 95 sm gacha. Qanoti 62—72 sm, yoyganda 2 m ga yetadi. Orqa oyogʻi barmogʻidagi tirnogʻining 4,2 sm dan uzunroq boʻlishi oʻziga xos belgilaridandir. Pat rangi toʻq qoʻngʻir, boshi malla. Burgut Yevropa, Osiyo va Shimoliy Amerikada keng tarqalgan. Oʻrta Osiyoda oʻtroq yashandi. Togʻ va choʻllarning odam yashamaydigan uzoq joylarida, qoyalar orasida, saksovulzorlarda uchraydi. Togʻ, choʻl va suv Bu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s6 {
            get {
                return ResourceManager.GetString("s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayiqlar  – yirtqichlar turkumiga mansub sut emizuvchilar oilasi. Eng yirik yirtqichlar, boshi katta, bo‘yni qisqa va yo‘g‘on. Panjalari kuchli rivojlangan, tovonida yuradi. Dumi kalta, kalin juni orasida deyarli sezilmaydi. Ko‘pchilik Ayiqlar o‘simlik xo‘r yoki aralash oziqlanadi. Ayiqlar odamga tegmaydi. Faqat oziq tanqis bo‘lganida, keksa va yarador ayiqlar odam uchun xavfli hisoblanadi. Oq ayiq esa haqiqiy yirtqich bo‘lib, odam uchun xavfli. Oq ayiq— ayiqsimonlar oilasiga mansub sut emizuvchi. Baʼzan alo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s7 {
            get {
                return ResourceManager.GetString("s7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoʻlbars— mushuksimonlar oilasiga mansub sut emizuvchi hayvon. Shu oilaning eng yirik vakili. Tanasining uzunligi 160—290 sm (baʼzan 3 m dan ortiq), dumi 114 sm gacha, vazni 390 kg gacha. Boshi yumaloq, mallarang , tanasining orqa va yon tomonlarida koʻndalang qora yoʻllari boʻladi. 7 ta kenja turi maʼlum. Gʻarbiy va Janubi-Sharqiy Osiyo hamda Hindiston yarim orolida tarqalgan. Rossiyaning Primorye oʻlkasida uchraydi. XX-asrning 30-yilgacha Kavkaz ortida, 50-yil gacha Amudaryoning quyi oqimida uchragan. Yo` [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s8 {
            get {
                return ResourceManager.GetString("s8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tulkilar — boʻrisimonlar oilasiga mansub sut emizuvchilar urugʻi. Tanasining uzunligi  40—90 sm, dumi 60 sm. Tanasi choʻziq, oyoklari nisbatan kalta. Uzun dumidagi moʻynasi baroq. Juni sariqdan to kumushqizgʻish (deyarli qoramtir) tusgacha. Tulkilarda mavsumiy va geografik dimorfizm kuchli namoyon boʻladi. 6— 11 turi maʼlum. Yevrosiyo, Afrika, Shimoliy Amerikada tarqalgan. Avstraliyaga ham olib kelingan. Oʻzbekistonda 2 turi (oddiy tulki, korsak) uchraydi. Ularning oziqlanish va yashash joyi xilmaxil: oʻrmo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s9 {
            get {
                return ResourceManager.GetString("s9", resourceCulture);
            }
        }
    }
}
